<!DOCTYPE html>
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD PHP & SQL</title>
</head>
<body>
    
    <h1>Sistema de vendas - CRUD PHP & SQL</h1>
    <hr>

    <p>Operações de <b>inserção</b>,
    <b>leitura</b>, <b>atualização</b> e 
    <b>exclusão</b> <b>de dados.</b>

    <hr>
    <h2>Escolha o que deseja gerenciar:</h2>
    <ul>
        <li><a href="fabricantes/visualizar.php">Fabricantes</a></li>
        <li><a href="">Produtos</a></li>
    </ul>
</p>
</body>
</html>